/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=prod --include-runtime=false apps/api/src/cloudflare-env.d.ts` (hash: 63a1f5d5ca53fd0f96aadfff6560123a)
interface __BaseEnv_Env {
	CACHE: KVNamespace;
	MEDIA: R2Bucket;
	DB: D1Database;
	ANALYTICS_DB: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	AI: Ai;
	ASSETS: Fetcher;
	ENVIRONMENT: "prod";
	SCOUT_ENABLED: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SCOUT_ENABLED">> {}
}
